### ISSUE TITLE
developer only tests feedback

### ISSUE THREAD

**Issue by chrstphrchvz** [timbunce/devel-nytprof#124]
1. Some of the developer tests run based on the presence of `.svn` directory while others check for `.git`. These should probably be consistent with which one (or both), or use some other means of enabling.

2. The file names portability test fails when enabled:

```
#   Failed test 'File names portability'
#   at t/92-file_port.t line 18.
# These files contain more than one dot in their name:
#    .indent.pro
#    .travis.yml
#    t/test02.pf.csv
#
# Looks like you failed 1 test of 1.
t/92-file_port.t .......
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests
```

**Comment by chrstphrchvz** [comment]
What I meant to say was,

1. Some of the developer tests run based on the presence of `.svn` directory while others check for `.git`. These should probably be consistent with which one (or both), or use some other means of enabling.

2. The file names portability test fails when enabled:

```
#   Failed test 'File names portability'
#   at t/92-file_port.t line 18.
# These files contain more than one dot in their name:
#    .indent.pro
#    .travis.yml
#    t/test02.pf.csv
#
# Looks like you failed 1 test of 1.
t/92-file_port.t .......
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests
```

**Comment by jkeenan** [comment]
>     1. Some of the developer tests run based on the presence of `.svn` directory while others check for `.git`. These should probably be consistent with which one (or both), or use some other means of enabling.
> 

We'll handle this problem separately in newly created ticket https://github.com/timbunce/devel-nytprof/issues/177.  Patches welcome!

>     2. The file names portability test fails when enabled:
> 
> 
> ```
> #   Failed test 'File names portability'
> #   at t/92-file_port.t line 18.
> # These files contain more than one dot in their name:
> #    .indent.pro
> #    .travis.yml
> #    t/test02.pf.csv
> #
> # Looks like you failed 1 test of 1.
> t/92-file_port.t .......
> Dubious, test returned 1 (wstat 256, 0x100)
> Failed 1/1 subtests
> ```

`t/92-file_port.t` has been moved to the `xt/` subdirectory, so it will no longer run as part of `make test` and no longer pose an obstacle to installation of this library.  Sooner or later we'll probably kill it altogether.

Closing this ticket.

Thank you very much.
Jim Keenan
