### ISSUE TITLE
Dead code list

### ISSUE THREAD

**Issue by marcespie** [timbunce/devel-nytprof#127]
I just used NYTProf to GC old code after some major refactor.

It was slightly painful, as you mostly have to read thru files and see lines which are left
blankly annotated.

I was wondering about the possibility to add a list/some coloring of methods which are NOT called in the profile at hand.  This would have come in handy in my case.

**Comment by jkeenan** [comment]
> I just used NYTProf to GC old code after some major refactor.
> 
> It was slightly painful, as you mostly have to read thru files and see lines which are left
> blankly annotated.
> 
> I was wondering about the possibility to add a list/some coloring of methods which are NOT called in the profile at hand. This would have come in handy in my case.

If your objective is to identify code which is no longer needed, have you considered using Devel::Cover?  I've long relied on that to identify code -- at least that in `*.pm` files -- which is not being reached and which may be removable?

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
> > I just used NYTProf to GC old code after some major refactor.
> > It was slightly painful, as you mostly have to read thru files and see lines which are left
> > blankly annotated.
> > I was wondering about the possibility to add a list/some coloring of methods which are NOT called in the profile at hand. This would have come in handy in my case.
> 
> If your objective is to identify code which is no longer needed, have you considered using Devel::Cover? I've long relied on that to identify code -- at least that in `*.pm` files -- which is not being reached and which may be removable?
> 

I will close this ticket at the end of the month unless we get a response from the OP.

**Comment by jkeenan** [comment]
> > > I just used NYTProf to GC old code after some major refactor.
> > > It was slightly painful, as you mostly have to read thru files and see lines which are left
> > > blankly annotated.
> > > I was wondering about the possibility to add a list/some coloring of methods which are NOT called in the profile at hand. This would have come in handy in my case.
> > 
> > 
> > If your objective is to identify code which is no longer needed, have you considered using Devel::Cover? I've long relied on that to identify code -- at least that in `*.pm` files -- which is not being reached and which may be removable?
> 
> I will close this ticket at the end of the month unless we get a response from the OP.

Closing as per schedule.
