### ISSUE TITLE
Missing Exporter.pm in test62-subcaller1

### ISSUE THREAD

**Issue by timsnyder** [timbunce/devel-nytprof#136]
I'm trying to build using perl 5.26.2 built by [conda-forge](https://github.com/conda-forge/perl-feedstock/blob/master/recipe/build.sh) and everything goes smoothly except that the results I get for test62-subcaller1 are missing the line for Exporter.pm in a few cases.

Attaching my output for [test62-subcaller1-missing-Exporter.txt](https://github.com/timbunce/devel-nytprof/files/3575515/test62-subcaller1-missing-Exporter.txt).  All other tests are passing.

Has anyone seen this behavior before?  If this is useful, I can provide steps to reproduce the build in a docker container.

cc: @msarahan, @mingwandroid, @jakirkham fyi.

**Comment by jkeenan** [comment]
> I'm trying to build using perl 5.26.2 built by [conda-forge](https://github.com/conda-forge/perl-feedstock/blob/master/recipe/build.sh) and everything goes smoothly except that the results I get for test62-subcaller1 are missing the line for Exporter.pm in a few cases.
> 
> Attaching my output for [test62-subcaller1-missing-Exporter.txt](https://github.com/timbunce/devel-nytprof/files/3575515/test62-subcaller1-missing-Exporter.txt). All other tests are passing.
> 
> Has anyone seen this behavior before? If this is useful, I can provide steps to reproduce the build in a docker container.
> 
> cc: @msarahan, @mingwandroid, @jakirkham fyi.

I am completely unfamiliar with conda-forge, but I addressed a problem with `t/test62-subcaller1*.t` in NYTPROF CPAN version 6.07, released this morning.

Can you give it a try?

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
> > I'm trying to build using perl 5.26.2 built by [conda-forge](https://github.com/conda-forge/perl-feedstock/blob/master/recipe/build.sh) and everything goes smoothly except that the results I get for test62-subcaller1 are missing the line for Exporter.pm in a few cases.
> > Attaching my output for [test62-subcaller1-missing-Exporter.txt](https://github.com/timbunce/devel-nytprof/files/3575515/test62-subcaller1-missing-Exporter.txt). All other tests are passing.
> > Has anyone seen this behavior before? If this is useful, I can provide steps to reproduce the build in a docker container.
> > cc: @msarahan, @mingwandroid, @jakirkham fyi.
> 
> I am completely unfamiliar with conda-forge, but I addressed a problem with `t/test62-subcaller1*.t` in NYTPROF CPAN version 6.07, released this morning.
> 
> Can you give it a try?
> 
> Thank you very much. Jim Keenan

We haven't heard back from the original poster in 2-1/2 years, so I'm closing this ticket.
