### ISSUE TITLE
"/home/utils/perl-5.14/5.14.1-nothreads-64/bin/nytprofhtml -d -m" command aborts early

### ISSUE THREAD

**Issue by Priyal3** [timbunce/devel-nytprof#137]
57% ... Can't call method "inc" on an undefined value at /home/utils/perl-5.14/5.14.1-nothreads-64/lib/site_perl/5.14.1/x86_64-linux/Devel/NYTProf/FileInfo.pm line 430.

**Comment by jkeenan** [comment]
We will need more context to help you diagnose this problem.  A new version of Devel-NYTProf (6.07) was released this morning.  Some of the code has shifted around.  Can you tell me whether the use of the `inc` method that was giving you problems is now located here?
```
435 sub filename_without_inc {
436     my $self = shift;
437     my $f    = [$self->filename];
438     strip_prefix_from_paths([$self->profile->inc], $f,  # <--- Is the problem here?
439         qr/(?: ^ | \[ | \sdefined\sat\s )/x
440     );
441     return $f->[0];
442 }
```
Or https://github.com/timbunce/devel-nytprof/blob/master/lib/Devel/NYTProf/FileInfo.pm#L438.

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
> We will need more context to help you diagnose this problem. A new version of Devel-NYTProf (6.07) was released this morning. Some of the code has shifted around. Can you tell me whether the use of the `inc` method that was giving you problems is now located here?
> 
> ```
> 435 sub filename_without_inc {
> 436     my $self = shift;
> 437     my $f    = [$self->filename];
> 438     strip_prefix_from_paths([$self->profile->inc], $f,  # <--- Is the problem here?
> 439         qr/(?: ^ | \[ | \sdefined\sat\s )/x
> 440     );
> 441     return $f->[0];
> 442 }
> ```
> 
> Or https://github.com/timbunce/devel-nytprof/blob/master/lib/Devel/NYTProf/FileInfo.pm#L438.
> 
> Thank you very much. Jim Keenan

We have not heard back from the original poster in 2-1/2 years, so I'm closing this ticket.
