### ISSUE TITLE
Changes: year for 6.07 should be 2021

### ISSUE THREAD

**Issue by shawnlaffan** [timbunce/devel-nytprof#152]
2020 should be 2021:  https://github.com/timbunce/devel-nytprof/blob/1f96b96ca46ab3b14fb00372989160c9b921c525/Changes#L7

**Comment by jkeenan** [comment]
> 2020 should be 2021:
> 
> https://github.com/timbunce/devel-nytprof/blob/1f96b96ca46ab3b14fb00372989160c9b921c525/Changes#L7

Good catch! Fixed in master in my development repository: d4926db

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
Correction to URL: https://github.com/jkeenan/devel-nytprof/commit/d4926db4878cbb0614b1d369d4b90902faa5b6b9
