### ISSUE TITLE
Migrate tickets from RT to github

### ISSUE THREAD

**Issue by timbunce** [timbunce/devel-nytprof#16]
Presumably via http://www.dagolden.com/index.php/1938/how-to-move-cpan-rt-tickets-to-github/ and the [followup](https://gist.github.com/markstos/5096483) in the comments.

**Comment by leejo** [comment]
https://github.com/leejo/rt-to-github might help with this

**Comment by timbunce** [comment]
Here's a [more recent article](http://www.dagolden.com/index.php/2397/moving-cpan-rt-tickets-to-github-now-improved/).

**Comment by leejo** [comment]
> Here's a more recent article.

Yep, and i've already deprecated my script in favour of that one :)

**Comment by timbunce** [comment]
I've used the script to migrate all the cases ([except one](https://github.com/dagolden/zzz-rt-to-github/issues/4)) to github.

**Comment by jkeenan** [comment]
In https://github.com/timbunce/devel-nytprof/issues/164, I have opened a ticket which I believe accurately reproduces the problem originally reported in https://rt.cpan.org/Public/Bug/Display.html?id=70211.  Hence, we can now deem all RT tickets migrated to GitHub issues and can close this issue.

Thank you very much.
Jim Keenan
