### ISSUE TITLE
Error 'File uses compression but compression is not supported by this build' in 6.08

### ISSUE THREAD

**Issue by perlpunk** [timbunce/devel-nytprof#169]
Version 6.08 fails in openSUSE tests:
https://build.opensuse.org/package/live_build_log/devel:languages:perl:autoupdate/perl-Devel-NYTProf/standard/x86_64

```
[   23s] t/10-run.t ............... ok
[   23s] File uses compression but compression is not supported by this build of NYTProf at /home/abuild/rpmbuild/BUILD/Devel-NYTProf-6.08/blib/lib/Devel/NYTProf/Data.pm line 89.
[   23s] t/11-reader.t ............ 
[   23s] Dubious, test returned 255 (wstat 65280, 0xff00)
[   23s] No subtests run 
[   23s] File uses compression but compression is not supported by this build of NYTProf at /home/abuild/rpmbuild/BUILD/Devel-NYTProf-6.08/blib/lib/Devel/NYTProf/Data.pm line 89.
[   23s] t/12-data.t .............. 
[   23s] Dubious, test returned 255 (wstat 65280, 0xff00)
[   23s] No subtests run 
[   23s] File uses compression but compression is not supported by this build of NYTProf at /home/abuild/rpmbuild/BUILD/Devel-NYTProf-6.08/blib/lib/Devel/NYTProf/Data.pm line 89.
[   23s] t/13-fileinfo.t .......... 
[   23s] Dubious, test returned 255 (wstat 65280, 0xff00)
[   23s] No subtests run 
[   23s] File uses compression but compression is not supported by this build of NYTProf at /home/abuild/rpmbuild/BUILD/Devel-NYTProf-6.08/blib/lib/Devel/NYTProf/Data.pm line 89.
[   23s] t/14-subinfo.t ........... 
[   23s] Dubious, test returned 255 (wstat 65280, 0xff00)
[   23s] No subtests run 
[   23s] t/22-readstream.t ........ ok
```

**Comment by jkeenan** [comment]
> Version 6.08 fails in openSUSE tests:
> https://build.opensuse.org/package/live_build_log/devel:languages:perl:autoupdate/perl-Devel-NYTProf/standard/x86_64
> 
> ```
> [   23s] File uses compression but compression is not supported by this build of NYTProf at /home/abuild/rpmbuild/BUILD/Devel-NYTProf-6.08/blib/lib/Devel/NYTProf/Data.pm line 89.
> [   23s] t/11-reader.t ............ 
> [   23s] Dubious, test returned 255 (wstat 65280, 0xff00)
> [   23s] No subtests run 
> [   23s] File uses compression but compression is not supported by this build of NYTProf at /home/abuild/rpmbuild/BUILD/Devel-NYTProf-6.08/blib/lib/Devel/NYTProf/Data.pm line 89.
> [   23s] t/12-data.t .............. 
> [   23s] Dubious, test returned 255 (wstat 65280, 0xff00)
> [   23s] No subtests run 
> [   23s] File uses compression but compression is not supported by this build of NYTProf at /home/abuild/rpmbuild/BUILD/Devel-NYTProf-6.08/blib/lib/Devel/NYTProf/Data.pm line 89.
> [   23s] t/13-fileinfo.t .......... 
> [   23s] Dubious, test returned 255 (wstat 65280, 0xff00)
> [   23s] No subtests run 
> [   23s] File uses compression but compression is not supported by this build of NYTProf at /home/abuild/rpmbuild/BUILD/Devel-NYTProf-6.08/blib/lib/Devel/NYTProf/Data.pm line 89.
> [   23s] t/14-subinfo.t ........... 
> [   23s] Dubious, test returned 255 (wstat 65280, 0xff00)
> [   23s] No subtests run 
> [snip]
> ```

@perlpunk, thank you for filing this report.

The root cause of the problem is that in yesterday's Devel-NYTProf-6.08 CPAN release, one of my major objectives was to increase test coverage.  Each of the 4 failing test files was added for that purpose.  Each such test file requires some dummy data provided in a file named, *e.g.,* `t/nytprof_11-reader.out.txt`, which I generated locally.  Each such data file contains compressed data -- but not all `perl` installations can handle such data.  Hence the error message.

I have previously observed failures like these on my Appveyor/Strawberry Perl configuration.  See, *e.g.*, https://ci.appveyor.com/project/jkeenan/devel-nytprof/builds/38912689.  Originally, I figured this was a Windows-specific problem; see https://github.com/timbunce/devel-nytprof/issues/163.  Since I don't have a Windows machine and could not immediately diagnose the problem further, I simply skipped those test files on Windows.
```
# Relax this restriction once we figure out how to make test $file work for
# Appveyor.
plan skip_all => "doesn't work without HAS_ZLIB" if (($^O eq "MSWin32") || ($^O eq 'VMS'));
```
However, it now appears that the problem is more perl-build-specific than OS-specific.

I made some preliminary attempts at diagnosing this problem in the [diagnose-zlib-problem-20210424 branch](https://github.com/jkeenan/devel-nytprof/tree/diagnose-zlib-problem-20210424) in my GH repository.

@perlpunk and everyone else:  The essential problem is:  **How can an individual test file determine whether the `perl` running the tests has compression or not?**

If we can answer that question, then we can develop a more precise `skip_all` condition for these test files.  (Ideally, we'll develop a better understanding of our test data.  But that's a larger problem and I'd like to partialize it and solve a smaller problem first.)

Thank you very much.
Jim Keenan

**Comment by perlpunk** [comment]
@jkeenan I can see this in the test output:
```
Compression: default level is 0, zlib version 0
```
So maybe checking for the `NYTP_ZLIB_VERSION` would be enough?

I can attach a `perl -V` output also if this helps.

**Comment by jkeenan** [comment]
On 4/28/21 10:31 AM, Tina Müller (tinita) wrote:
> @jkeenan <https://github.com/jkeenan> I can see this in the test output:
> 
> |Compression: default level is 0, zlib version 0 |
> 
> So maybe checking for the |NYTP_ZLIB_VERSION| would be enough?
> 
> I can attach a |perl -V| output also if this helps.
> 

Please do!  I will try to get back to this problem later today.

**Comment by perlpunk** [comment]
```
% perl -V
Summary of my perl5 (revision 5 version 32 subversion 1) configuration:
   
  Platform:
    osname=linux
    osvers=5.11.15-1-default
    archname=x86_64-linux-thread-multi
    uname='reproducible'
    config_args='-ds -e -Dprefix=/usr -Dvendorprefix=/usr -Dinstallusrbinperl -Dusethreads -Di_db -Di_dbm -Di_ndbm -Di_gdbm -Dd_dbm_open -Duseshrplib=true -Doptimize=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -Wall -pipe -Accflags=-DPERL_USE_SAFE_PUTENV -Dotherlibdirs=/usr/lib/perl5/site_perl -Dinc_version_list=5.32.0/x86_64-linux-thread-multi 5.32.0'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-D_REENTRANT -D_GNU_SOURCE -DPERL_USE_SAFE_PUTENV -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -Wall -pipe'
    cppflags='-D_REENTRANT -D_GNU_SOURCE -DPERL_USE_SAFE_PUTENV -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong'
    ccversion=''
    gccversion='10.3.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -L/usr/local/lib64 -fstack-protector-strong'
    libpth=/usr/local/lib /usr/lib64/gcc/x86_64-suse-linux/10/include-fixed /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/lib /usr/lib /lib/../lib64 /usr/lib/../lib64 /lib /lib64 /usr/lib64 /usr/local/lib64
    libs=-lm -ldl -lcrypt -lpthread
    perllibs=-lm -ldl -lcrypt -lpthread
    libc=/lib64/libc-2.33.so
    so=so
    useshrplib=true
    libperl=libperl.so
    gnulibc_version='2.33'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E -Wl,-rpath,/usr/lib/perl5/5.32.1/x86_64-linux-thread-multi/CORE'
    cccdlflags='-fPIC'
    lddlflags='-shared -L/usr/local/lib64 -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_IMPLICIT_CONTEXT
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
    USE_THREAD_SAFE_LOCALE
  Built under linux
  Compiled at Mar 14 2021 00:00:00
  %ENV:
    PERL_HASH_SEED="42"
  @INC:
    /usr/lib/perl5/site_perl/5.32.1/x86_64-linux-thread-multi
    /usr/lib/perl5/site_perl/5.32.1
    /usr/lib/perl5/vendor_perl/5.32.1/x86_64-linux-thread-multi
    /usr/lib/perl5/vendor_perl/5.32.1
    /usr/lib/perl5/5.32.1/x86_64-linux-thread-multi
    /usr/lib/perl5/5.32.1
    /usr/lib/perl5/site_perl
```

**Comment by jkeenan** [comment]
@perlpunk , could you take a look at this p.r.?
https://github.com/timbunce/devel-nytprof/pull/171

Alternatively, could you check out the https://github.com/timbunce/devel-nytprof/tree/gh-163-169-has-zlib branch and give it a spin on the openSUSE platform where you observed the original problem?

Thank you very much.
Jim Keenan

**Comment by perlpunk** [comment]
@jkeenan yes, this is working, thanks! I used the 6.08_001 tarball which made it a bit easier.

**Comment by jkeenan** [comment]
This should be closable now that v6.09 has been released.

**Comment by perlpunk** [comment]
Thanks! version 6.09 on its way to devel:languages:perl
