### ISSUE TITLE
NYTProf organization

### ISSUE THREAD

**Issue by Leont** [timbunce/devel-nytprof#179]
I propose a NYTProf github organization is set up, so the work of its maintenance can more easily be distributed.

It's probably easiest if @timbunce does this himself, since he can actually transfer the repository.

After that we can invite people with an interest in maintaining and improving Devel::NYTProf.

**Comment by timbunce** [comment]
> I propose a NYTProf github organization is set up, so the work of its maintenance can more easily be distributed.

Hi Leon. Sounds good to me. Any thoughts @jkeenan?

Bike shed time... what shall we call it? Just "nytprof", or "perl-nytprof" or "devel-nytprof", or ...?

**Comment by timbunce** [comment]
After some pondering over the weekend I've decided not to take the github organization route for now.

The existing collaboration mechanisms are working well enough. I'm especially grateful to James for his considerable recent efforts, and mindful that he might tire of the work at some point. I hope he won't be disappointed by this decision. We can always revisit it later.

Meanwhile, issues are pull requests are welcome from anyone interested in making improvements.
