### ISSUE TITLE
nytprofhtml assumes that nytprofcalls is in PATH

### ISSUE THREAD

**Issue by stro** [timbunce/devel-nytprof#21]
In nytprofhtml, line 798, there's system call to "nytprofcalls", assuming that Perl's directory for binary executables is in PATH. This is true for system Perl, but it's not for custom-built Perl installations. 

To work correctly, it should be something like File::Spec->cat($Config::Config{'bin'}, 'nytprofcalls') instead.

**Comment by zhouzhen1** [comment]
using $Config::Config{'bin'} for the path causes problem in our company as we install CPAN modules to custom paths instead of the perl core interpreter's path. Why not do it like below?
```
use FindBin qw($Bin);
File::Spec->cat($Bin, 'nytprofcalls');
```
