### ISSUE TITLE
Enhancement request: progress meters when processing nytprof.out

### ISSUE THREAD

**Issue by DrHyde** [timbunce/devel-nytprof#28]
When profiling some code recently I got ...

" Extracting subroutine call data (there were 2253748752 of them, so this may take some time) ... "

And yes, it did "take some time" - over 12 hours. Some kind of visible progress meter showing the amount of work done so far would be nice to have.

**Comment by jkeenan** [comment]
@timbunce addressed this issue back in 2014, so this ticket is now closable.  Doing so.

Thank you very much.
Jim Keenan
