### ISSUE TITLE
Test t/test25-strevalb.t fails under perl-5.20.1

### ISSUE THREAD

**Issue by cschwenz** [timbunce/devel-nytprof#43]
cschwenz@cochin:~/local/src/perl-modules/Devel-NYTProf-5.06$ ~/local/perl-5.20.1/bin/perl Makefile.PL
    Looking for header files and functions...
    Found clock_gettime in time.h
    Found deflateInit2 in zlib.h
    Your perl was compiled with gcc (version 4.4.3), okay.
    Checking if your kit is complete...
    Looks good
    Generating a Unix-style Makefile
    Writing Makefile for Devel::NYTProf
    Writing MYMETA.yml and MYMETA.json
    cschwenz@cochin:~/local/src/perl-modules/Devel-NYTProf-5.06$ make
    cp lib/Devel/NYTProf/Constants.pm blib/lib/Devel/NYTProf/Constants.pm
    cp lib/Devel/NYTProf/js/jit/gradient50.png blib/lib/Devel/NYTProf/js/jit/gradient50.png
    cp lib/Devel/NYTProf/js/desc.png blib/lib/Devel/NYTProf/js/desc.png
    cp lib/Devel/NYTProf/js/jquery-min.js blib/lib/Devel/NYTProf/js/jquery-min.js
    cp lib/Devel/NYTProf/js/jquery-tablesorter-min.js blib/lib/Devel/NYTProf/js/jquery-tablesorter-min.js
    cp lib/Devel/NYTProf/SubCallInfo.pm blib/lib/Devel/NYTProf/SubCallInfo.pm
    cp lib/Devel/NYTProf/Test.pm blib/lib/Devel/NYTProf/Test.pm
    cp lib/Devel/NYTProf/js/jit/gradient.png blib/lib/Devel/NYTProf/js/jit/gradient.png
    cp lib/Devel/NYTProf/FileInfo.pm blib/lib/Devel/NYTProf/FileInfo.pm
    cp lib/Devel/NYTProf/js/jit/gradient30.png blib/lib/Devel/NYTProf/js/jit/gradient30.png
    cp lib/Devel/NYTProf/Apache.pm blib/lib/Devel/NYTProf/Apache.pm
    cp lib/Devel/NYTProf/js/jit/Treemap.css blib/lib/Devel/NYTProf/js/jit/Treemap.css
    cp lib/Devel/NYTProf/Util.pm blib/lib/Devel/NYTProf/Util.pm
    cp lib/Devel/NYTProf/ReadStream.pm blib/lib/Devel/NYTProf/ReadStream.pm
    cp lib/Devel/NYTProf/FileHandle.pm blib/lib/Devel/NYTProf/FileHandle.pm
    cp lib/Devel/NYTProf/js/jit/jit.js blib/lib/Devel/NYTProf/js/jit/jit.js
    cp lib/Devel/NYTProf/Run.pm blib/lib/Devel/NYTProf/Run.pm
    cp lib/Devel/NYTProf/Core.pm blib/lib/Devel/NYTProf/Core.pm
    cp lib/Devel/NYTProf/Data.pm blib/lib/Devel/NYTProf/Data.pm
    cp lib/Devel/NYTProf/SubInfo.pm blib/lib/Devel/NYTProf/SubInfo.pm
    cp lib/Devel/NYTProf/Reader.pm blib/lib/Devel/NYTProf/Reader.pm
    cp lib/Devel/NYTProf/js/asc.png blib/lib/Devel/NYTProf/js/asc.png
    cp lib/Devel/NYTProf/js/style-tablesorter.css blib/lib/Devel/NYTProf/js/style-tablesorter.css
    cp lib/Devel/NYTProf/js/jit/gradient20.png blib/lib/Devel/NYTProf/js/jit/gradient20.png
    cp lib/Devel/NYTProf/js/jit/gradient-cushion1.png blib/lib/Devel/NYTProf/js/jit/gradient-cushion1.png
    cp lib/Devel/NYTProf.pm blib/lib/Devel/NYTProf.pm
    cp lib/Devel/NYTProf/js/bg.png blib/lib/Devel/NYTProf/js/bg.png
    cp lib/Devel/NYTProf/js/jit/jit-yc.js blib/lib/Devel/NYTProf/js/jit/jit-yc.js
    cp MemoryProfiling.pod blib/lib/Devel/MemoryProfiling.pod
    cp lib/Devel/NYTProf/js/jit/gradient40.png blib/lib/Devel/NYTProf/js/jit/gradient40.png
    Running Mkbootstrap for Devel::NYTProf ()
    chmod 644 "NYTProf.bs"
    "/home/cschwenz/local/perl-5.20.1/bin/perl" "/home/cschwenz/local/perl-5.20.1/lib/5.20.1/ExtUtils/xsubpp"  -typemap "/home/cschwenz/local/perl-5.20.1/lib/5.20.1/ExtUtils/typemap" -typemap "typemap"  FileHandle.xs > FileHandle.xsc && mv FileHandle.xsc FileHandle.c
    gcc -c   -D_REENTRANT -D_GNU_SOURCE -DPERL_REENTRANT_MAXSIZE=1048576 -DPERL_HASH_FUNC_SIPHASH -DPERL_PERTURB_KEYS_RANDOM -fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector -I/home/cschwenz/local/include -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g   -DVERSION=\"5.06\" -DXS_VERSION=\"5.06\" -fPIC "-I/home/cschwenz/local/perl-5.20.1/lib/5.20.1/x86_64-linux-thread-multi-ld/CORE"  -DHAS_CLOCK_GETTIME -DHAS_ZLIB -W -Wall -Wpointer-arith -Wbad-function-cast -Wno-comment -Wno-sign-compare -Wno-cast-qual -Wmissing-noreturn -Wno-unused-parameter FileHandle.c
    FileHandle.xs: In function ‘NYTP_write_attribute_nv’:
    FileHandle.xs:920: warning: format ‘%g’ expects type ‘double’, but argument 4 has type ‘NV’
    FileHandle.xs:920: warning: format ‘%g’ expects type ‘double’, but argument 4 has type ‘NV’
    "/home/cschwenz/local/perl-5.20.1/bin/perl" "/home/cschwenz/local/perl-5.20.1/lib/5.20.1/ExtUtils/xsubpp"  -typemap "/home/cschwenz/local/perl-5.20.1/lib/5.20.1/ExtUtils/typemap" -typemap "typemap"  NYTProf.xs > NYTProf.xsc && mv NYTProf.xsc NYTProf.c
    gcc -c   -D_REENTRANT -D_GNU_SOURCE -DPERL_REENTRANT_MAXSIZE=1048576 -DPERL_HASH_FUNC_SIPHASH -DPERL_PERTURB_KEYS_RANDOM -fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector -I/home/cschwenz/local/include -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g   -DVERSION=\"5.06\" -DXS_VERSION=\"5.06\" -fPIC "-I/home/cschwenz/local/perl-5.20.1/lib/5.20.1/x86_64-linux-thread-multi-ld/CORE"  -DHAS_CLOCK_GETTIME -DHAS_ZLIB -W -Wall -Wpointer-arith -Wbad-function-cast -Wno-comment -Wno-sign-compare -Wno-cast-qual -Wmissing-noreturn -Wno-unused-parameter NYTProf.c
    NYTProf.xs: In function ‘open_output_file’:
    NYTProf.xs:1769: warning: format ‘%.6f’ expects type ‘double’, but argument 3 has type ‘NV’
    NYTProf.xs: In function ‘close_output_file’:
    NYTProf.xs:1799: warning: format ‘%.6f’ expects type ‘double’, but argument 2 has type ‘NV’
    NYTProf.xs: In function ‘finish_profile’:
    NYTProf.xs:2960: warning: format ‘%g’ expects type ‘double’, but argument 2 has type ‘NV’
    NYTProf.c: At top level:
    NYTProf.xs:1137: warning: ‘get_str_id’ defined but not used
    rm -f blib/arch/auto/Devel/NYTProf/NYTProf.so
    LD_RUN_PATH="/usr/lib:/home/cschwenz/local/lib" gcc  -shared -O2 -g -L/home/cschwenz/local/lib -L/usr/local/lib -fstack-protector FileHandle.o NYTProf.o  -o blib/arch/auto/Devel/NYTProf/NYTProf.so 	\
           -lrt -lz  	\
          
    chmod 755 blib/arch/auto/Devel/NYTProf/NYTProf.so
    "/home/cschwenz/local/perl-5.20.1/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- NYTProf.bs blib/arch/auto/Devel/NYTProf/NYTProf.bs 644
    cp blib/arch/auto/Devel/NYTProf/NYTProf.so blib/lib/Devel/auto/Devel/NYTProf/NYTProf.so
    cp bin/nytprofcsv blib/script/nytprofcsv
    "/home/cschwenz/local/perl-5.20.1/bin/perl" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/nytprofcsv
    cp bin/nytprofhtml blib/script/nytprofhtml
    "/home/cschwenz/local/perl-5.20.1/bin/perl" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/nytprofhtml
    cp bin/flamegraph.pl blib/script/flamegraph.pl
    "/home/cschwenz/local/perl-5.20.1/bin/perl" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/flamegraph.pl
    cp bin/nytprofcalls blib/script/nytprofcalls
    "/home/cschwenz/local/perl-5.20.1/bin/perl" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/nytprofcalls
    cp bin/nytprofmerge blib/script/nytprofmerge
    "/home/cschwenz/local/perl-5.20.1/bin/perl" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/nytprofmerge
    cp bin/nytprofcg blib/script/nytprofcg
    "/home/cschwenz/local/perl-5.20.1/bin/perl" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/nytprofcg
    Manifying 5 pod documents
    Manifying 9 pod documents
    cschwenz@cochin:~/local/src/perl-modules/Devel-NYTProf-5.06$ make test
    Running Mkbootstrap for Devel::NYTProf ()
    chmod 644 "NYTProf.bs"
    cp blib/arch/auto/Devel/NYTProf/NYTProf.so blib/lib/Devel/auto/Devel/NYTProf/NYTProf.so
    PERL_DL_NONLAZY=1 "/home/cschwenz/local/perl-5.20.1/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
    t/00-load.t ............ 1/2 # Testing Devel::NYTProf 5.06 started at Mon Feb  9 12:29:57 2015
    # Compression: default level is 6, zlib version 1.2.8
    # --- Perl 5.020001 Config on x86_64-linux-thread-multi-ld:
    # 	d_gettimeod: define
    # 	d_sysconf: define
    t/00-load.t ............ ok   
    t/10-run.t ............. ok       
    t/22-readstream.t ...... ok    
    t/30-util.t ............ ok     
    t/31-env.t ............. ok   
    t/40-savesrc.t ......... ok       
    t/42-global.t .......... ok       
    t/44-model.t ........... ok     
    t/50-errno.t ........... ok   
    t/60-forkdepth.t ....... ok   
    t/68-hashline.t ........ skipped: Currently a developer-only test
    t/70-subname.t ......... ok    
    t/71-moose.t ........... skipped: Test is incomplete (has no results defined yet)
    t/72-autodie.t ......... skipped: Currently a developer-only test
    t/80-version.t ......... ok   
    t/90-pod.t ............. ok     
    t/91-pod_coverage.t .... skipped: Currently a developer-only test
    t/92-file_port.t ....... skipped: Test::Portability::Files required for testing filename portability. Can't locate Test/Portability/Files.pm
    t/test01.t ............. ok       
    t/test02.t ............. ok       
    t/test03.t ............. ok       
    t/test05.t ............. ok       
    t/test06.t ............. ok       
    t/test07.t ............. ok       
    t/test08.t ............. ok       
    t/test09.t ............. ok       
    t/test10.t ............. ok       
    t/test11.t ............. ok       
    t/test12.t ............. ok       
    t/test13.t ............. ok       
    t/test14.t ............. ok     
    t/test16.t ............. 1/113 given is experimental at test16.p line 10.
    when is experimental at test16.p line 11.
    when is experimental at test16.p line 14.
    t/test16.t ............. 3/113 given is experimental at test16.p line 10.
    when is experimental at test16.p line 11.
    when is experimental at test16.p line 14.
    given is experimental at test16.p line 10.
    when is experimental at test16.p line 11.
    when is experimental at test16.p line 14.
    given is experimental at test16.p line 10.
    when is experimental at test16.p line 11.
    when is experimental at test16.p line 14.
    given is experimental at test16.p line 10.
    when is experimental at test16.p line 11.
    when is experimental at test16.p line 14.
    given is experimental at test16.p line 10.
    when is experimental at test16.p line 11.
    when is experimental at test16.p line 14.
    given is experimental at test16.p line 10.
    when is experimental at test16.p line 11.
    when is experimental at test16.p line 14.
    t/test16.t ............. 45/113 given is experimental at test16.p line 10.
    when is experimental at test16.p line 11.
    when is experimental at test16.p line 14.
    given is experimental at test16.p line 10.
    when is experimental at test16.p line 11.
    when is experimental at test16.p line 14.
    given is experimental at test16.p line 10.
    when is experimental at test16.p line 11.
    when is experimental at test16.p line 14.
    given is experimental at test16.p line 10.
    when is experimental at test16.p line 11.
    when is experimental at test16.p line 14.
    given is experimental at test16.p line 10.
    when is experimental at test16.p line 11.
    when is experimental at test16.p line 14.
    t/test16.t ............. 81/113 given is experimental at test16.p line 10.
    when is experimental at test16.p line 11.
    when is experimental at test16.p line 14.
    given is experimental at test16.p line 10.
    when is experimental at test16.p line 11.
    when is experimental at test16.p line 14.
    given is experimental at test16.p line 10.
    when is experimental at test16.p line 11.
    when is experimental at test16.p line 14.
    given is experimental at test16.p line 10.
    when is experimental at test16.p line 11.
    when is experimental at test16.p line 14.
    t/test16.t ............. ok       
    t/test17-goto.t ........ ok     
    t/test18-goto2.t ....... ok     
    t/test20-streval.t ..... ok       
    t/test21-streval3.t .... ok       
    t/test22-strevala.t .... ok       
    t/test23-strevall.t .... ok     
    t/test24-strevalc.t .... ok     
    t/test25-strevalb.t .... 1/145 perl: op.c:12011: Perl_rpeep: Assertion `(kid->op_type == OP_NULL && kid->op_targ == OP_NEXTSTATE) || kid->op_type == OP_STUB || kid->op_type == OP_ENTER' failed.
    Exit status 6 from /home/cschwenz/local/perl-5.20.1/bin/perl -d:NYTProf at t/test25-strevalb.t line 23.
    Profile data incomplete, no terminator for 1 pids (refer to TROUBLESHOOTING in the documentation)
    Use of uninitialized value in division (/) at /home/cschwenz/local/src/perl-modules/Devel-NYTProf-5.06/blib/lib/Devel/NYTProf/Data.pm line 113, <DATA> line 6.
    Use of uninitialized value in subtraction (-) at /home/cschwenz/local/src/perl-modules/Devel-NYTProf-5.06/blib/lib/Devel/NYTProf/Data.pm line 114, <DATA> line 6.
    
    #   Failed test 'undef isa 'Devel::NYTProf::SubInfo''
    #   at t/test25-strevalb.t line 34.
    #     undef isn't defined
    
    #   Failed test at t/lib/NYTProfTest.pm line 172.
    # Test group aborted: Can't call method "subname" on an undefined value at t/test25-strevalb.t line 35, <DATA> line 6.
    # Looks like you planned 145 tests but ran 4.
    # Looks like you failed 2 tests of 4 run.
    t/test25-strevalb.t .... Dubious, test returned 2 (wstat 512, 0x200)
    Failed 143/145 subtests 
    t/test30-fork-0.t ...... ok       
    t/test40pmc.t .......... ok       
    t/test50-disable.t ..... ok       
    t/test51-enable.t ...... ok       
    t/test60-subname.t ..... ok     
    t/test61-submerge.t .... ok     
    t/test62-subcaller1.t .. ok     
    t/test70-subexcl.t ..... ok     
    t/test80-recurs.t ...... ok     
    t/test81-swash.t ....... ok     
    t/test82-version.t ..... ok     
    t/test90-strsubref.t ... ok     
    t/zzz.t ................ 1/? # Tests ended at Mon Feb  9 12:32:13 2015
    t/zzz.t ................ ok   
    
    Test Summary Report
    -------------------
    t/test25-strevalb.t  (Wstat: 512 Tests: 4 Failed: 2)
      Failed tests:  3-4
      Non-zero exit status: 2
      Parse errors: Bad plan.  You planned 145 tests but ran 4.
    Files=53, Tests=4521, 136 wallclock secs ( 1.52 usr  0.14 sys + 77.08 cusr 13.07 csys = 91.81 CPU)
    Result: FAIL
    Failed 1/53 test programs. 2/4521 subtests failed.
    make: *** [test_dynamic] Error 255
    cschwenz@cochin:~/local/src/perl-modules/Devel-NYTProf-5.06$ ~/local/perl-5.20.1/bin/perl -V
    Summary of my perl5 (revision 5 version 20 subversion 1) configuration:
       
      Platform:
        osname=linux, osvers=2.6.32-71-server, archname=x86_64-linux-thread-multi-ld
        uname='linux evl3300811 2.6.32-71-server #138-ubuntu smp thu dec 18 17:51:53 utc 2014 x86_64 gnulinux '
        config_args='-Dcc=gcc -Dprefix=/home/cschwenz/local/perl-5.20.1 -Dusethreads -Accflags=-DPERL_REENTRANT_MAXSIZE=1048576 -Duselargefiles -Duse64bitall -Duselongdouble -Accflags=-DPERL_HASH_FUNC_SIPHASH -Accflags=-DPERL_PERTURB_KEYS_RANDOM -Dinc_version_list=none -DEBUGGING=both -DNO_MATHOMS -Dperladmin=cschwenz@cpan.org -Dcf_email=cschwenz@cpan.org'
        hint=recommended, useposix=true, d_sigaction=define
        useithreads=define, usemultiplicity=define
        use64bitint=define, use64bitall=define, uselongdouble=define
        usemymalloc=n, bincompat5005=undef
      Compiler:
        cc='gcc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -DPERL_REENTRANT_MAXSIZE=1048576 -DPERL_HASH_FUNC_SIPHASH -DPERL_PERTURB_KEYS_RANDOM -fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector -I/home/cschwenz/local/include -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
        optimize='-O2 -g',
        cppflags='-D_REENTRANT -D_GNU_SOURCE -DPERL_REENTRANT_MAXSIZE=1048576 -DPERL_HASH_FUNC_SIPHASH -DPERL_PERTURB_KEYS_RANDOM -fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector -I/home/cschwenz/local/include -I/usr/local/include'
        ccversion='', gccversion='4.4.3', gccosandvers=''
        intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
        d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
        ivtype='long', ivsize=8, nvtype='long double', nvsize=16, Off_t='off_t', lseeksize=8
        alignbytes=16, prototype=define
      Linker and Libraries:
        ld='gcc', ldflags ='-fstack-protector -L/home/cschwenz/local/lib -L/usr/local/lib'
        libpth=/home/cschwenz/local/lib /usr/local/lib /usr/lib/gcc/x86_64-linux-gnu/4.4.3/include-fixed /usr/lib /lib/../lib /usr/lib/../lib /lib /lib64 /usr/lib64
        libs=-lnsl -ldl -lm -lcrypt -lutil -lpthread -lc
        perllibs=-lnsl -ldl -lm -lcrypt -lutil -lpthread -lc
        libc=libc-2.11.1.so, so=so, useshrplib=true, libperl=libperl.so
        gnulibc_version='2.11.1'
      Dynamic Linking:
        dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E -Wl,-rpath,/home/cschwenz/local/perl-5.20.1/lib/5.20.1/x86_64-linux-thread-multi-ld/CORE'
        cccdlflags='-fPIC', lddlflags='-shared -O2 -g -L/home/cschwenz/local/lib -L/usr/local/lib -fstack-protector'
    
    
    Characteristics of this binary (from libperl): 
      Compile-time options: DEBUGGING HAS_TIMES MULTIPLICITY PERLIO_LAYERS
                            PERL_DONT_CREATE_GVSV PERL_HASH_FUNC_SIPHASH
                            PERL_IMPLICIT_CONTEXT PERL_MALLOC_WRAP
                            PERL_NEW_COPY_ON_WRITE PERL_PERTURB_KEYS_RANDOM
                            PERL_PRESERVE_IVUV PERL_TRACK_MEMPOOL USE_64_BIT_ALL
                            USE_64_BIT_INT USE_ITHREADS USE_LARGE_FILES
                            USE_LOCALE USE_LOCALE_COLLATE USE_LOCALE_CTYPE
                            USE_LOCALE_NUMERIC USE_LONG_DOUBLE USE_PERLIO
                            USE_PERL_ATOF USE_REENTRANT_API
      Built under linux
      Compiled at Jan 16 2015 12:30:38
      %ENV:
        PERL_CPANM_HOME="/home/cschwenz/.local-cpanm"
        PERL_CPANM_OPT="--verbose --from=https://cpan.metacpan.org --auto-cleanup=1 --interactive --prompt"
      @INC:
        /home/cschwenz/local/perl-5.20.1/lib/site_perl/5.20.1/x86_64-linux-thread-multi-ld
        /home/cschwenz/local/perl-5.20.1/lib/site_perl/5.20.1
        /home/cschwenz/local/perl-5.20.1/lib/5.20.1/x86_64-linux-thread-multi-ld
        /home/cschwenz/local/perl-5.20.1/lib/5.20.1
        .
    cschwenz@cochin:~/local/src/perl-modules/Devel-NYTProf-5.06$

**Comment by timbunce** [comment]
Hi @cschwenz. Thanks for the report.
5.20.1 [works for some people](http://matrix.cpantesters.org/?dist=Devel-NYTProf+5.06). Since it's an assert failure I'd guess you're hitting it because your build has DEBUGGING enabled. Seems that 5.21.6+ is broken for all.
I'll take a look.

**Comment by timbunce** [comment]
I believe this is fixed in master now. Thanks.
