### ISSUE TITLE
"given is experimental" warnings [rt.cpan.org #91988]

### ISSUE THREAD

**Issue by timbunce** [timbunce/devel-nytprof#49]
Migrated from [rt.cpan.org#91988](https://rt.cpan.org/Ticket/Display.html?id=91988) (status was 'new')

Requestors:
- zefram@fysh.org

Attachments:
- [given_experimental.patch](https://rt.cpan.org/Ticket/Attachment/1310042/694284/given_experimental.patch)

From zefram@fysh.org on 2014-01-09 16:42:54:

```
There's a test using given/when that on recent perls generates warnings
about given/when being experimental.  The test should muffle the warning.
Attached patch fixes.

-zefram
```

**Comment by toddr** [comment]
Submitted pull request #98 to fix this.

**Comment by jkeenan** [comment]
> Migrated from [rt.cpan.org#91988](https://rt.cpan.org/Ticket/Display.html?id=91988) (status was 'new')
> 
> Requestors:
> 
>     * [zefram@fysh.org](mailto:zefram@fysh.org)
> 
> 
> Attachments:
> 
>     * [given_experimental.patch](https://rt.cpan.org/Ticket/Attachment/1310042/694284/given_experimental.patch)
> 
> 
> From [zefram@fysh.org](mailto:zefram@fysh.org) on 2014-01-09 16:42:54:
> 
> ```
> There's a test using given/when that on recent perls generates warnings
> about given/when being experimental.  The test should muffle the warning.
> Attached patch fixes.
> 
> -zefram
> ```

The pull request created by @toddr was applied on Nov 24 2016.  Since there have been no further problems reported I am closing this ticket.

Thank you very much.
Jim Keenan
