### ISSUE TITLE
 [rt.cpan.org #70211]

### ISSUE THREAD

**Issue by timbunce** [timbunce/devel-nytprof#53]
Migrated from [rt.cpan.org#70211](https://rt.cpan.org/Ticket/Display.html?id=70211) (status was 'open')

Requestors:
- bohica@ntlworld.com

From bohica@ntlworld.com on 2011-08-11 10:11:25:

```

```

From timb@cpan.org on 2012-12-26 17:06:24:

```
I can reproduce in perl 5.14 but not 5.16 (or 5.17) so I'm inclined to consider it a perl bug.
I'll dig a little deeper anyway to try to identify the cause and see if a workaround is possible.
```

From zefram@fysh.org on 2013-07-02 14:48:40:

```

```

**Comment by timbunce** [comment]
This issues [had problems being imported from RT](https://github.com/dagolden/zzz-rt-to-github/issues/4).

**Comment by jkeenan** [comment]
Superseded by https://github.com/timbunce/devel-nytprof/issues/164; closing this ticket.
