### ISSUE TITLE
v5.07 not building with Perl 5.8.8?

### ISSUE THREAD

**Issue by zhouzhen1** [timbunce/devel-nytprof#62]
I am getting below error when I tried to build it with our company's Perl 5.8.8. (Building with other Perls like 5.10 were fine. ) What could be the problem there? 

```
FileHandle.xs:62: error: syntax error before "tTHX"
FileHandle.xs:62: warning: no semicolon at end of struct or union
FileHandle.xs:75: error: syntax error before '}' token
FileHandle.xs: In function `NYTP_tell':
FileHandle.xs:95: error: dereferencing pointer to incomplete type
FileHandle.xs:96: error: dereferencing pointer to incomplete type
FileHandle.xs:97: error: dereferencing pointer to incomplete type
FileHandle.xs:97: error: dereferencing pointer to incomplete type
FileHandle.xs:101: error: dereferencing pointer to incomplete type
FileHandle.xs:102: error: dereferencing pointer to incomplete type
FileHandle.xs: In function `NYTP_type_of_offset':
FileHandle.xs:109: error: dereferencing pointer to incomplete type
FileHandle.xs:120: error: dereferencing pointer to incomplete type
FileHandle.xs: In function `compressed_io_croak':
FileHandle.xs:144: error: dereferencing pointer to incomplete type
FileHandle.xs:156: error: dereferencing pointer to incomplete type
FileHandle.xs: In function `NYTP_start_deflate':
...
```

Also tried 5.06, it's fine with Perl 5.8.8.

**Comment by kamal2222ahmed** [comment]
perl Makefile.PL
Looking for header files and functions...
Found clock_gettime in time.h
Found deflateInit2 in zlib.h
Assertion testing enabled
Your perl was compiled with gcc (version 3.4.6 20060404 (Red Hat 3.4.6-3)), okay.
Checking if your kit is complete...
Looks good
Writing Makefile for Devel::NYTProf
Writing MYMETA.yml and MYMETA.json
kahmed@vm-devqa08 ~/devel-nytprof $ make
cp lib/Devel/NYTProf/js/bg.png blib/lib/Devel/NYTProf/js/bg.png
cp lib/Devel/NYTProf/js/jquery-tablesorter-min.js blib/lib/Devel/NYTProf/js/jquery-tablesorter-min.js
cp lib/Devel/NYTProf/js/jquery-min.js blib/lib/Devel/NYTProf/js/jquery-min.js
cp lib/Devel/NYTProf/Run.pm blib/lib/Devel/NYTProf/Run.pm
cp lib/Devel/NYTProf/js/asc.png blib/lib/Devel/NYTProf/js/asc.png
cp lib/Devel/NYTProf/Data.pm blib/lib/Devel/NYTProf/Data.pm
cp lib/Devel/NYTProf/SubInfo.pm blib/lib/Devel/NYTProf/SubInfo.pm
cp lib/Devel/NYTProf/js/desc.png blib/lib/Devel/NYTProf/js/desc.png
cp lib/Devel/NYTProf/FileInfo.pm blib/lib/Devel/NYTProf/FileInfo.pm
cp lib/Devel/NYTProf/Reader.pm blib/lib/Devel/NYTProf/Reader.pm
cp lib/Devel/NYTProf/Test.pm blib/lib/Devel/NYTProf/Test.pm
cp lib/Devel/NYTProf/ReadStream.pm blib/lib/Devel/NYTProf/ReadStream.pm
cp lib/Devel/NYTProf.pm blib/lib/Devel/NYTProf.pm
cp lib/Devel/NYTProf/js/jit/jit.js blib/lib/Devel/NYTProf/js/jit/jit.js
cp lib/Devel/NYTProf/js/jit/gradient.png blib/lib/Devel/NYTProf/js/jit/gradient.png
cp lib/Devel/NYTProf/js/jit/gradient-cushion1.png blib/lib/Devel/NYTProf/js/jit/gradient-cushion1.png
cp lib/Devel/NYTProf/js/jit/gradient20.png blib/lib/Devel/NYTProf/js/jit/gradient20.png
cp lib/Devel/NYTProf/js/jit/gradient40.png blib/lib/Devel/NYTProf/js/jit/gradient40.png
cp lib/Devel/NYTProf/Core.pm blib/lib/Devel/NYTProf/Core.pm
cp lib/Devel/NYTProf/Apache.pm blib/lib/Devel/NYTProf/Apache.pm
cp lib/Devel/NYTProf/SubCallInfo.pm blib/lib/Devel/NYTProf/SubCallInfo.pm
cp lib/Devel/NYTProf/js/jit/gradient30.png blib/lib/Devel/NYTProf/js/jit/gradient30.png
cp lib/Devel/NYTProf/FileHandle.pm blib/lib/Devel/NYTProf/FileHandle.pm
cp MemoryProfiling.pod blib/lib/Devel/MemoryProfiling.pod
cp lib/Devel/NYTProf/js/jit/gradient50.png blib/lib/Devel/NYTProf/js/jit/gradient50.png
cp lib/Devel/NYTProf/Util.pm blib/lib/Devel/NYTProf/Util.pm
cp lib/Devel/NYTProf/Constants.pm blib/lib/Devel/NYTProf/Constants.pm
cp lib/Devel/NYTProf/js/style-tablesorter.css blib/lib/Devel/NYTProf/js/style-tablesorter.css
cp lib/Devel/NYTProf/js/jit/jit-yc.js blib/lib/Devel/NYTProf/js/jit/jit-yc.js
cp lib/Devel/NYTProf/js/jit/Treemap.css blib/lib/Devel/NYTProf/js/jit/Treemap.css
/usr/coderyte/bin/perl /usr/coderyte/lib/perl5/5.8.8/ExtUtils/xsubpp  -typemap /usr/coderyte/lib/perl5/5.8.8/ExtUtils/typemap -typemap typemap  FileHandle.xs > FileHandle.xsc && mv FileHandle.xsc FileHandle.c
cc -c   -fPIC -D_REENTRANT -D_GNU_SOURCE -DTHREADS_HAVE_PIDS -fno-strict-aliasing -pipe -Wdeclaration-after-statement -I/usr/local/include -DDEBUGGING -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/include/gdbm -O2   -DVERSION=\"5.07\" -DXS_VERSION=\"5.07\" -fpic "-I/usr/coderyte/lib/perl5/5.8.8/x86_64-linux-thread-multi/CORE"  -DHAS_CLOCK_GETTIME -DHAS_ZLIB -DUSE_HARD_ASSERT -W -Wall -Wpointer-arith -Wbad-function-cast -Wno-comment -Wno-sign-compare -Wno-cast-qual -Wmissing-noreturn -Wno-unused-parameter FileHandle.c
FileHandle.xs:62: error: expected specifier-qualifier-list before ‘tTHX’
FileHandle.xs: In function ‘NYTP_tell’:
FileHandle.xs:95: error: ‘struct NYTP_file_t’ has no member named ‘state’
FileHandle.xs:96: error: ‘struct NYTP_file_t’ has no member named ‘state’
FileHandle.xs:97: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:97: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:101: error: ‘struct NYTP_file_t’ has no member named ‘my_perl’
FileHandle.xs: In function ‘NYTP_type_of_offset’:
FileHandle.xs:109: error: ‘struct NYTP_file_t’ has no member named ‘state’
FileHandle.xs:120: error: ‘struct NYTP_file_t’ has no member named ‘state’
FileHandle.xs: In function ‘compressed_io_croak’:
FileHandle.xs:144: error: ‘struct NYTP_file_t’ has no member named ‘state’
FileHandle.xs:156: error: ‘struct NYTP_file_t’ has no member named ‘state’
FileHandle.xs: In function ‘NYTP_start_deflate’:
FileHandle.xs:167: error: ‘struct NYTP_file_t’ has no member named ‘state’
FileHandle.xs:168: error: ‘struct NYTP_file_t’ has no member named ‘state’
FileHandle.xs:169: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:169: error: ‘struct NYTP_file_t’ has no member named ‘large_buffer’
FileHandle.xs:170: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:171: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:171: error: ‘struct NYTP_file_t’ has no member named ‘small_buffer’
FileHandle.xs:172: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:173: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:174: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:175: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:177: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:181: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs: In function ‘NYTP_start_inflate’:
FileHandle.xs:190: error: ‘struct NYTP_file_t’ has no member named ‘state’
FileHandle.xs:191: error: ‘struct NYTP_file_t’ has no member named ‘state’
FileHandle.xs:193: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:193: error: ‘struct NYTP_file_t’ has no member named ‘small_buffer’
FileHandle.xs:194: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:195: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:195: error: ‘struct NYTP_file_t’ has no member named ‘large_buffer’
FileHandle.xs:196: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:197: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:198: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:199: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:201: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:203: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs: In function ‘NYTP_open’:
FileHandle.xs:222: error: ‘struct NYTP_file_t’ has no member named ‘my_perl’
FileHandle.xs:225: error: ‘struct NYTP_file_t’ has no member named ‘state’
FileHandle.xs:226: error: ‘struct NYTP_file_t’ has no member named ‘count’
FileHandle.xs:227: error: ‘struct NYTP_file_t’ has no member named ‘stdio_at_eof’
FileHandle.xs:228: error: ‘struct NYTP_file_t’ has no member named ‘zlib_at_eof’
FileHandle.xs:230: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs: In function ‘grab_input’:
FileHandle.xs:242: error: ‘struct NYTP_file_t’ has no member named ‘count’
FileHandle.xs:243: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:243: error: ‘struct NYTP_file_t’ has no member named ‘large_buffer’
FileHandle.xs:244: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:253: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:253: error: ‘struct NYTP_file_t’ has no member named ‘stdio_at_eof’
FileHandle.xs:254: error: ‘struct NYTP_file_t’ has no member named ‘small_buffer’
FileHandle.xs:260: error: ‘struct NYTP_file_t’ has no member named ‘my_perl’
FileHandle.xs:263: error: ‘struct NYTP_file_t’ has no member named ‘stdio_at_eof’
FileHandle.xs:266: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:267: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:267: error: ‘struct NYTP_file_t’ has no member named ‘small_buffer’
FileHandle.xs:278: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:288: error: ‘struct NYTP_file_t’ has no member named ‘stdio_at_eof’
FileHandle.xs:292: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:294: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:297: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:299: error: ‘struct NYTP_file_t’ has no member named ‘zlib_at_eof’
FileHandle.xs: In function ‘NYTP_read_unchecked’:
FileHandle.xs:311: error: ‘struct NYTP_file_t’ has no member named ‘my_perl’
FileHandle.xs:316: error: ‘struct NYTP_file_t’ has no member named ‘state’
FileHandle.xs:320: error: ‘struct NYTP_file_t’ has no member named ‘state’
FileHandle.xs:325: error: ‘struct NYTP_file_t’ has no member named ‘large_buffer’
FileHandle.xs:325: error: ‘struct NYTP_file_t’ has no member named ‘count’
FileHandle.xs:326: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:330: error: ‘struct NYTP_file_t’ has no member named ‘count’
FileHandle.xs:335: error: ‘struct NYTP_file_t’ has no member named ‘count’
FileHandle.xs:339: error: ‘struct NYTP_file_t’ has no member named ‘zlib_at_eof’
FileHandle.xs: In function ‘NYTP_gets’:
FileHandle.xs:370: error: ‘struct NYTP_file_t’ has no member named ‘state’
FileHandle.xs:372: error: ‘struct NYTP_file_t’ has no member named ‘large_buffer’
FileHandle.xs:372: error: ‘struct NYTP_file_t’ has no member named ‘count’
FileHandle.xs:373: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:403: error: ‘struct NYTP_file_t’ has no member named ‘zlib_at_eof’
FileHandle.xs:412: error: ‘struct NYTP_file_t’ has no member named ‘state’
FileHandle.xs:415: error: ‘struct NYTP_file_t’ has no member named ‘my_perl’
FileHandle.xs: In function ‘sync_avail_out_to_ftell’:
FileHandle.xs:446: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs: In function ‘flush_output’:
FileHandle.xs:459: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:459: error: ‘struct NYTP_file_t’ has no member named ‘large_buffer’
FileHandle.xs:472: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:476: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:476: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:487: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:489: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:489: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:490: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:491: error: ‘struct NYTP_file_t’ has no member named ‘small_buffer’
FileHandle.xs:492: error: ‘struct NYTP_file_t’ has no member named ‘small_buffer’
FileHandle.xs:502: error: ‘struct NYTP_file_t’ has no member named ‘my_perl’
FileHandle.xs:507: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:507: error: ‘struct NYTP_file_t’ has no member named ‘small_buffer’
FileHandle.xs:508: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:510: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:517: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:522: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:522: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs: In function ‘NYTP_write’:
FileHandle.xs:535: error: ‘struct NYTP_file_t’ has no member named ‘state’
FileHandle.xs:541: error: ‘struct NYTP_file_t’ has no member named ‘my_perl’
FileHandle.xs:551: error: ‘struct NYTP_file_t’ has no member named ‘state’
FileHandle.xs:556: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:557: error: ‘struct NYTP_file_t’ has no member named ‘large_buffer’
FileHandle.xs:557: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:561: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:568: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs: In function ‘NYTP_printf’:
FileHandle.xs:584: error: ‘struct NYTP_file_t’ has no member named ‘state’
FileHandle.xs:588: error: ‘struct NYTP_file_t’ has no member named ‘my_perl’
FileHandle.xs: In function ‘NYTP_flush’:
FileHandle.xs:600: error: ‘struct NYTP_file_t’ has no member named ‘state’
FileHandle.xs:605: error: ‘struct NYTP_file_t’ has no member named ‘my_perl’
FileHandle.xs: In function ‘NYTP_eof’:
FileHandle.xs:614: error: ‘struct NYTP_file_t’ has no member named ‘state’
FileHandle.xs:615: error: ‘struct NYTP_file_t’ has no member named ‘zlib_at_eof’
FileHandle.xs:619: error: ‘struct NYTP_file_t’ has no member named ‘my_perl’
FileHandle.xs: In function ‘NYTP_fstrerror’:
FileHandle.xs:627: error: ‘struct NYTP_file_t’ has no member named ‘state’
FileHandle.xs:627: error: ‘struct NYTP_file_t’ has no member named ‘state’
FileHandle.xs:628: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:632: error: ‘struct NYTP_file_t’ has no member named ‘my_perl’
FileHandle.xs: In function ‘NYTP_close’:
FileHandle.xs:641: error: ‘struct NYTP_file_t’ has no member named ‘my_perl’
FileHandle.xs:645: error: ‘struct NYTP_file_t’ has no member named ‘state’
FileHandle.xs:646: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:646: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:650: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:650: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:654: error: ‘struct NYTP_file_t’ has no member named ‘state’
FileHandle.xs:655: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:664: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:668: error: ‘struct NYTP_file_t’ has no member named ‘state’
FileHandle.xs:669: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs:671: error: ‘struct NYTP_file_t’ has no member named ‘zs’
FileHandle.xs: In function ‘NYTP_write_comment’:
FileHandle.xs:880: error: ‘struct NYTP_file_t’ has no member named ‘state’
FileHandle.xs:882: error: ‘struct NYTP_file_t’ has no member named ‘my_perl’
FileHandle.xs: In function ‘write_time_common’:
FileHandle.xs:1122: error: ‘struct NYTP_file_t’ has no member named ‘my_perl’
make: *** [FileHandle.o] Error 1
kahmed@vm-devqa08 ~/devel-nytprof $ perl -V
Summary of my perl5 (revision 5 version 8 subversion 8) configuration:
  Platform:
    osname=linux, osvers=2.6.9-42.0.3.elsmp, archname=x86_64-linux-thread-multi
    uname='linux odin.coderyte.ad 2.6.9-42.0.3.elsmp #1 smp mon sep 25 17:24:31 edt 2006 x86_64 x86_64 x86_64 gnulinux '
    config_args=''
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=undef use64bitall=undef uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-fPIC -D_REENTRANT -D_GNU_SOURCE -DTHREADS_HAVE_PIDS -fno-strict-aliasing -pipe -Wdeclaration-after-statement -I/usr/local/include -DDEBUGGING -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/include/gdbm',
    optimize='-O2',
    cppflags='-D_REENTRANT -D_GNU_SOURCE -DTHREADS_HAVE_PIDS -fno-strict-aliasing -pipe -Wdeclaration-after-statement -I/usr/local/include -DDEBUGGING -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/include/gdbm'
    ccversion='', gccversion='3.4.6 20060404 (Red Hat 3.4.6-3)', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='cc', ldflags ='-L/usr/coderyte/lib -L/usr/local/lib -L/usr/local/lib64'
    libpth=/usr/coderyte/lib /usr/local/lib /usr/local/lib64 /lib /lib64 /usr/lib /usr/lib64
    libs=-lnsl -lgdbm -ldb -ldl -lm -lcrypt -lutil -lpthread -lc
    perllibs=-lnsl -ldl -lm -lcrypt -lutil -lpthread -lc
    libc=/lib/libc-2.3.4.so, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version='2.3.4'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/coderyte/lib -L/usr/local/lib -L/usr/local/lib64'


Characteristics of this binary (from libperl): 
  Compile-time options: DEBUGGING MULTIPLICITY PERL_IMPLICIT_CONTEXT
                        PERL_MALLOC_WRAP THREADS_HAVE_PIDS USE_ITHREADS
                        USE_LARGE_FILES USE_PERLIO USE_REENTRANT_API
  Locally applied patches:
	ActivePerl Build 819
	Iin_load_module moved for compatibility with build 806
	PerlEx support in CGI::Carp
	Less verbose ExtUtils::Install and Pod::Find
	Patch for CAN-2005-0448 from Debian with modifications
	Rearrange @INC so that 'site' is searched before 'perl'
	Partly reverted 24733 to preserve binary compatibility
	28671 Define PERL_NO_DEV_RANDOM on Windows
	28376 Add error checks after execing PL_cshname or PL_sh_path
	28305 Pod::Html should not convert "foo" into ``foo''
	27736 Make perl_fini() run with Sun WorkShop compiler
	27619 Bug in Term::ReadKey being triggered by a bug in Term::ReadLine
	27549 Move DynaLoader.o into libperl.so
	27528 win32_pclose() error exit doesn't unlock mutex
	27527 win32_async_check() can loop indefinitely
	27515 ignore directories when searching @INC
	27359 Fix -d:Foo=bar syntax
	27210 Fix quote typo in c2ph
	27203 Allow compiling swigged C++ code
	27200 Make stat() on Windows handle trailing slashes correctly
	27194 Get perl_fini() running on HP-UX again
	27133 Initialise lastparen in the regexp structure
	27034 Avoid "Prototype mismatch" warnings with autouse
	26970 Make Passive mode the default for Net::FTP
	26921 Avoid getprotobyname/number calls in IO::Socket::INET
	26897,26903 Make common IPPROTO_* constants always available
	26670 Make '-s' on the shebang line parse -foo=bar switches
	26536 INSTALLSCRIPT versus INSTALLDIRS
	26379 Fix alarm() for Windows 2003
	26087 Storable 0.1 compatibility
	25861 IO::File performace issue
	25084 long groups entry could cause memory exhaustion
	24699 ICMP_UNREACHABLE handling in Net::Ping
  Built under linux
  Compiled at Aug 16 2013 15:03:53
Also not compiling with Perl 5.8.8 , on CentOs 6.4

**Comment by kamal2222ahmed** [comment]
i tried to install Devel-NYTProf-3.11_90, even though some of the *.t tests get skipped as they still need Perl 5.10, but i was able to install 3.11. either we think Perl 5.8.8 should be supported ( which is highly unlikely ) , or we have a metrix on Which version of NYTProf is supported by which version of Perl. I vote to close this issue as resolved

**Comment by kamal2222ahmed** [comment]
nm, Tim already answered it in 2012
http://matrix.cpantesters.org/?dist=Devel-NYTProf%204.06;maxver=1

**Comment by kamal2222ahmed** [comment]
so i installed 5.06 on centos 6.4 using the tar.gz distro. but seems nytprof saves results as prof.out and not nytprof.out
perl -MDevel::NYTProf -e 'print "$Devel::NYTProf::VERSION\n"'
5.06

kahmed@vm-devqa08 ~/NYTRUN $ nytprofhtml -f prof.out 
Reading prof.out
NYTProf data format error while parsing header at /usr/coderyte/lib/perl5/site_perl/5.8.8/x86_64-linux-thread-multi/Devel/NYTProf/Data.pm line 87.
kahmed@vm-devqa08 ~/NYTRUN $ nytprofhtml
Reading nytprof.out
Failed to open input 'nytprof.out': No such file or directory at /usr/coderyte/lib/perl5/site_perl/5.8.8/x86_64-linux-thread-multi/Devel/NYTProf/Data.pm line 87.


line 87:
79 sub new {
 80     my $class = shift;
 81     my $args = shift || { };
 82 
 83     my $file = $args->{filename} ||= 'nytprof.out';
 84 
 85     print "Reading $file\n" unless $args->{quiet};
 86 
 87     my $profile = load_profile_data_from_file(
 88         $file,
 89         $args->{callback},
 90     );

**Comment by zhouzhen1** [comment]
Well, personally I think it's fine we just drop support for Perl 5.8.8. The community should phase out ancient Perl versions to move onto the new ones.

**Comment by timbunce** [comment]
I'd be happy to apply a patch that fixes it, but don't have time to develop one myself. Upgrading from Perl 5.8.8 to even just 5.8.9 would avoid the problem.

**Comment by zhouzhen1** [comment]
Tim, it's fine. Please focus on things of more importance. Let me just close this issue.
