### ISSUE TITLE
strawberry perl (MS Windows) 5.22.0 test failures

### ISSUE THREAD

**Issue by kmx** [timbunce/devel-nytprof#76]
Hi, 

here is the test failure I have experienced on strawberry perl 5.22.0 (32bit)
https://gist.github.com/kmx/fcc9b9d12303c0ecd9c8

-- kmx

**Comment by timbunce** [comment]
Thanks. Closing this now as cpantesters indicates [the tests are passing for the latest dev release](http://matrix.cpantesters.org/?dist=Devel-NYTProf%206.02_90).

**Comment by shawnlaffan** [comment]
See also comment https://github.com/timbunce/devel-nytprof/issues/94#issuecomment-376365731
