### ISSUE TITLE
Remove or fix link to the demo (documentation)

### ISSUE THREAD

**Issue by pmorch** [timbunce/devel-nytprof#80]
The [perldoc](http://search.cpan.org/dist/Devel-NYTProf/bin/nytprofhtml#SAMPLE_OUTPUT) contains:
> SAMPLE OUTPUT
> 
> You can see a complete report for a large application (over 200 files and 2000 subroutines) at https://www.me.com/ix/tim.bunce/Public/perl/nytprof/nytprof-perlcritic-demo/index.html

However, navigating to that URL redirects to https://www.icloud.com/ .

Is there a better demo URL?

**Comment by timbunce** [comment]
Thanks!

**Comment by pmorch** [comment]
Sure!

And for any googlers out there searching for an URL for an example nytprof report, the new correct link is: http://timbunce.github.io/devel-nytprof/sample-report/nytprof-20160319/index.html
