### ISSUE TITLE
Wrong link are generated for FlameGraph

### ISSUE THREAD

**Issue by KES777** [timbunce/devel-nytprof#83]
See errors on picture
![nytdebug-bug1](https://cloud.githubusercontent.com/assets/799021/9445460/ec301940-4a94-11e5-91b8-68a78ea9fe2f.png)

Clicking on the link shows:

```
Filename    /home/feelsafe/perl5/lib/perl5/Plack/Middleware/Debug/TraceENV.pm
Statements  Executed 0 statements in 0s
```

The generated html is:
https://gist.github.com/KES777/ec2a42ba7d9781a024d5

**Comment by timbunce** [comment]
I think you're the only one to report this so it seems like something specific to your code/setup.
A small test case would be a big help!

**Comment by KES777** [comment]
No, I have not sources from that time and nytprof reports.

**Comment by jkeenan** [comment]
> No, I have not sources from that time and nytprof reports.

No further info provided in 5-1/2 years; closing.
